"""
Beats + Playwright actions for the main Dashboard tutorial video, on
portal.phixtra.com's demo merchant account — see tutorial_studio/lib.py for
the shared machinery this module plugs into.

Covers the Dashboard redesign V1 (all 4 phases, see
project_phixtra_connect_dashboard_redesign memory): Sales Overview KPIs +
date picker, Sales Pipeline snapshot, Lead Sources, Channel Activity,
Campaign Performance, Needs Attention, Recent Activity. Deliberately never
clicks through to another page (a Pipeline stage, a lead, the Inbox) even
though several elements here are real links — those destinations are their
own separate videos (CRM & Sales Pipeline, Campaigns) per the approved
Phase 4 plan; this one stays a Dashboard-only walkthrough.
"""
from playwright.sync_api import TimeoutError as PWTimeoutError

BASE_URL = "https://portal.phixtra.com"
DEMO_EMAIL = "demo@phixtra.com"
DEMO_PASSWORD = "Demo1234!"

BEATS = {
    "b1_landing": (
        "This is the Fixtra Dashboard — the first thing a business owner "
        "sees after logging in. Not a chat log. A real sales operation, "
        "at a glance."
    ),
    "b1_kpis": (
        "Four numbers up top: sales actually won this month, the value "
        "sitting in the pipeline right now, new leads this month, and the "
        "conversion rate from lead to won deal. Each one compares itself "
        "to the period before it."
    ),
    "b1_period_open": (
        "Every number on this page responds to the date range picked up "
        "here. Let's switch it."
    ),
    "b1_period_after": (
        "Same screen — this quarter's numbers instead. Nothing else to "
        "click. The whole page just recalculated on its own."
    ),
    "b2_pipeline": (
        "Below that, the Sales Pipeline — every open deal, grouped by "
        "stage, with how many there are and how much they're worth."
    ),
    "b2_stage": (
        "Click any stage and it takes you straight to those leads on the "
        "Pipeline Board. The dashboard doesn't just display information — "
        "it's a way in."
    ),
    "b2_sources": (
        "Right next to it, Lead Sources — not just where leads come from, "
        "but how much revenue each source has actually produced."
    ),
    "b3_channel": (
        "Channel Activity shows WhatsApp conversations for the period — "
        "total, new, and how many are still waiting on a reply."
    ),
    "b3_locked": (
        "Instagram and Messenger are shown honestly as coming soon. No "
        "invented numbers for channels that aren't connected yet."
    ),
    "b4_campaign": (
        "Campaign Performance follows a WhatsApp campaign the whole way "
        "through — sent, delivered, read, replied, opportunities, and won."
    ),
    "b4_revenue": (
        "And the number that actually matters: revenue generated by "
        "campaigns, with each individual campaign broken out underneath."
    ),
    "b5_attention": (
        "Needs Attention flags exactly three things worth chasing — leads "
        "gone quiet, proposals waiting too long, and deals stuck in a "
        "stage. No guesswork. Real, rule-based flags."
    ),
    "b5_activity": (
        "And Recent Activity — every new lead, stage move, WhatsApp "
        "reply, and win, in one feed. Click any line and it opens that "
        "record."
    ),
    "b6_close": (
        "That's the whole Fixtra Dashboard — sales, pipeline, channels, "
        "campaigns, and what needs attention, all on one page, running on "
        "real data."
    ),
}


def login(browser, video_dir):
    login_ctx = browser.new_context(viewport={"width": 1440, "height": 1000})
    login_page = login_ctx.new_page()
    login_page.goto(f"{BASE_URL}/login", wait_until="networkidle")
    login_page.fill("input[name=email]", DEMO_EMAIL)
    login_page.fill("input[name=password]", DEMO_PASSWORD)
    login_page.click("button[type=submit]")
    try:
        login_page.wait_for_url(f"{BASE_URL}/dashboard", timeout=15000)
    except PWTimeoutError:
        raise RuntimeError(f"LOGIN FAILED — current URL: {login_page.url}")
    storage_state = login_ctx.storage_state()
    login_ctx.close()

    # service_workers="block" mirrors campaigns.py — the portal's sw.js
    # would otherwise intercept fetches ahead of Playwright's network layer.
    ctx = browser.new_context(
        viewport={"width": 1440, "height": 1000},
        storage_state=storage_state,
        record_video_dir=str(video_dir),
        record_video_size={"width": 1440, "height": 1000},
        service_workers="block",
    )
    ctx.add_init_script("localStorage.setItem('phixtra_tour_done', '1');")
    page = ctx.new_page()
    return page, ctx


def record(page, hold, mark, beat_ms):
    # --- b1_landing: land on the dashboard, default period (this month) ---
    page.goto(f"{BASE_URL}/dashboard", wait_until="networkidle", timeout=20000)
    hold("b1_landing")

    # --- b1_kpis: camera drifts across the 4 KPI cards ---
    page.locator("#dashSalesOverview").scroll_into_view_if_needed()
    hold("b1_kpis", motion=[
        "#dashSalesOverview .kpi-card:nth-child(1)",
        "#dashSalesOverview .kpi-card:nth-child(2)",
        "#dashSalesOverview .kpi-card:nth-child(3)",
        "#dashSalesOverview .kpi-card:nth-child(4)",
    ])

    # --- b1_period_open: highlight the date-range picker, no action yet ---
    hold("b1_period_open", motion=["select[name=period]"])

    # --- b1_period_after: actually switch period (real reload), hold on
    #     the recalculated KPI row so the change is visibly proven, not
    #     just claimed in narration ---
    page.select_option("select[name=period]", value="this_quarter")
    page.wait_for_load_state("networkidle")
    page.locator("#dashSalesOverview").scroll_into_view_if_needed()
    hold("b1_period_after", motion=[
        "#dashSalesOverview .kpi-card:nth-child(1)",
        "#dashSalesOverview .kpi-card:nth-child(2)",
    ])

    # --- b2_pipeline: Sales Pipeline snapshot ---
    page.locator("#dashPipelineCard").scroll_into_view_if_needed()
    hold("b2_pipeline")

    # --- b2_stage: highlight one stage row — never click, stays off the
    #     real Pipeline Board (that's its own, separate video) ---
    hold("b2_stage", motion=["#dashPipelineCard .frow"])

    # --- b2_sources: Lead Sources card ---
    page.locator("#dashSourcesCard").scroll_into_view_if_needed()
    hold("b2_sources")

    # --- b3_channel: Channel Activity, real WhatsApp card ---
    page.locator("#dashChannelActivity").scroll_into_view_if_needed()
    hold("b3_channel", motion=["#dashChannelActivity > div:nth-child(1)"])

    # --- b3_locked: the two honest "coming soon" cards ---
    hold("b3_locked", motion=[
        "#dashChannelActivity > div:nth-child(2)",
        "#dashChannelActivity > div:nth-child(3)",
    ])

    # --- b4_campaign: Campaign Performance funnel ---
    page.locator("#dashCampaignCard").scroll_into_view_if_needed()
    hold("b4_campaign")

    # --- b4_revenue: the revenue line + per-campaign breakdown ---
    page.locator("#dashCampaignCard .camp-row").first.scroll_into_view_if_needed()
    hold("b4_revenue")

    # --- b5_attention: rule-based Needs Attention card ---
    page.locator("#dashAttentionCard").scroll_into_view_if_needed()
    hold("b5_attention")

    # --- b5_activity: Recent Activity feed ---
    page.locator("#dashActivityCard").scroll_into_view_if_needed()
    hold("b5_activity")

    # --- b6_close: bookend back on the KPI row for a clean closing shot ---
    page.locator("#dashSalesOverview").scroll_into_view_if_needed()
    hold("b6_close")
